# <a id='7'>Q1. Write a Python program to get the string from the given string where all the occurrence of its first char has been changed to '$,' except first char itself?<a/> 


Sample String: 'prospect'

Expected Result : 'pros$ect'

In [1]:
def change_character(x):
    for i in range(1,len(x),1):
        if x[i] == x[0]:
            x = x[0:i] + '$' + x[i+1:]
    return x                    

In [2]:
answer1 = change_character('prospect')
print(answer1)

pros$ect


# <a id='7'>Q2. Write a Python program to get the single string from the two given strings, and separated by the space and swap the first two characters of each string?<a/>             

In [ ]:
Sample String : 'abc', 'xyz'
Expected Result: 'xyc abz'

In [3]:
def swapString(a , b):
    return (b[0:2] + a[2:] + " " + a[0:2] + b[2:])

In [4]:
swapString('abc' , 'xyz')

'xyc abz'

# <a id='7'>Q3. Write the Python program to add 'ing' at the end of the given string (length of the string should be at least 3). If given string already ends with 'ing,' then add 'ly' instead. If string length of the given string is less than 3, leave it unchanged?<a/> 

In [ ]:
Sample string: ' abc '
Expectedresult: 'abcing'
    
Samplestring: 'string'
Expectedresult: 'stringly'

In [5]:
def add_string(x):
    if len(x) < 2:
        x = x
    else:
        if x[-3:len('string')] == 'ing':
            x = x + 'ly'
        else:
            x = x + 'ing'
    return x

print(add_string('abc'))
print(add_string('string'))

abcing
stringly


# <a id='7'>Q4. Write the Python program to find the first appearance of the substring 'not' and 'poor' from the given string, if 'not' follows the 'poor', replace the whole 'not'...' poor' substring with 'good'.Return the resulting string.'<a/> 

Sample string: 'The lyrics are not that poor!' 
               'The lyrics are poor!' 

Expected Result: 'The lyrics are good!' 
                 'The lyrics are poor!    

In [10]:
def not_poor(str1):
    isnot = str1.find('not')
    ispoor = str1.find('poor')
  

    if ispoor > isnot and isnot>0 and ispoor>0:
        str1 = str1.replace(str1[isnot:(ispoor+4)], 'good')
        return str1
    else:
        return str1
print(not_poor('The lyrics is not that poor!'))
print(not_poor('The lyrics is poor!'))

The lyrics is good!
The lyrics is poor!


# <a id='7'> Q5. Write the Python program to remove the characters which have odd index values of a given string.<a/> 


In [12]:
def str_Odd(x):
    y = ''
    for i in range(0,len(x),1):
        if i%2 == 0:
            y = y+x[i]
    return y

str_Odd('extravagant')

'etaaat'

# <a id='7'>Q6. Write the Python function to get a string made of 4 copies of the last two characters of the specified string (length must be at least 2).<a/> 
 
Sample function and result :
    
insert-end ('Python') -> abababab
    
insert-end('Exercises') -> jkjkjkjk

In [19]:
def str_copy(str):
    return str[-2:] * 4

str_copy('Python')

'onononon'

In [20]:
str_copy('Exercises')

'eseseses'

# <a id='7'>Q7. Write the python function to get a string made of its first three characters of a specified string. If the length of the string is less than 3 then return the original string.<a/> 


In [ ]:
Sample function and result : 
first-three('ipy') -> ipy 
first-three('python') -> pyt

In [2]:
def Cut_str(s):
    if len(s) < 3:
        s = s
    else:
        s = s[:3]
    return s

print(Cut_str('ipy'))
print(Cut_str('python'))

ipy
pyt


# <a id='7'>Q8. Write the python program to print the following floating numbers up to 2 decimal places?<a/> 

In [ ]:
23.456789

In [3]:
print('%0.2f'%(23.456789))

23.46


# <a id='7'>Q9. Write the Python program to format a number with a percentage?<a/> 

In [4]:
def converter(num):
    print("Converted Number with percentage: "+"{:.2%}".format(num))

In [6]:
converter(0.2345)

Converted Number with percentage: 23.45%


# <a id='7'>Q10. Write the Python program to count occurrences of a substring in a String?<a/> 

In [9]:
'stringstr'.count('str')

2

# <a id='7'>Q11. Write the Python program to count repeated characters in a string.<a/> 

Sample string: ' thequickbrownjumpsoverthelazydog '

Expected output:

o3 

e3 

u2 

h2    

In [12]:
# first i decided to build a function that only returns the count of all letters
from itertools import combinations
import collections

In [22]:
my_list = 'thequickbrownjumpsoverthelazydog'

def Countfreq(my_list):
    return collections.Counter(my_list)

frequency = collections.Counter(my_list)
frequency

Counter({'t': 2,
         'h': 2,
         'e': 3,
         'q': 1,
         'u': 2,
         'i': 1,
         'c': 1,
         'k': 1,
         'b': 1,
         'r': 2,
         'o': 3,
         'w': 1,
         'n': 1,
         'j': 1,
         'm': 1,
         'p': 1,
         's': 1,
         'v': 1,
         'l': 1,
         'a': 1,
         'z': 1,
         'y': 1,
         'd': 1,
         'g': 1})

In [23]:
# building the function to answer the question
def repeat_count(str):
    for i in set(str):
        if str.count(i) > 1:
            print(i,str.count(i))

In [24]:
repeat_count(my_list)

o 3
e 3
u 2
t 2
h 2
r 2


# <a id='7'>Q12. Write the Python program to print the square and cube symbol in the area of a rectangle and volume of a cylinder?<a/> 


In [ ]:
Sample output-
The area of the rectangle is 1256.66cm2
The volume of the cylinder is 1254.725cm3

In [27]:
area = 1256.66
volume = 1254.725
print('The Area of rectangle is {} cm\u00b2'.format(area))
print('The Volumne of cylinder is {} cm\u00b3'.format(volume))

The Area of rectangle is 1256.66 cm²
The Volumne of cylinder is 1254.725 cm³


# <a id='7'>Q13. Write the Python program to check if a string contains all letters of the alphabet?<a/> 

In [28]:
def alphabet_str(str):
    for i in list(map(chr,range(97,123))):
        if i not in str:
            x = 'All alphabets not present'
            break
        else:
            x = 'All alphabets present'
    return x

In [29]:
alphabet_str('Joshua')

'All alphabets not present'

In [31]:
all_alph = 'a','b','c','d','e','f','g','h','i','j','k','l','m','n','o','p','q','r','s','t','u','v','w','x','y','z'

In [33]:
alphabet_str(all_alph)

'All alphabets present'

In [ ]:
#OR

In [35]:
alphabet_str(list(map(chr,range(97,123))))

'All alphabets present'

# <a id='7'>Q14. Write the Python program to find the second most repeated word in a given string?<a/> 


In [36]:
def sec_most_rep(str):
    str = str.split()
    count = {}
    for i in set(str):
        count[i] = str.count(i)
    print(sorted(count.items(),key= lambda x:(x[1],x[0]))[-2])

In [38]:
sec_most_rep('The big black cat jumped over the lazy dog . The big black dog is really lazy')

('dog', 2)


In [39]:
sec_most_rep('Mary is a good girl . She is going to be great man as he is good')

('good', 2)


# <a id='7'>Q15. Write the Python program to find the minimum window in the given string, which will contains all the characters of another given strings?<a/>


In [ ]:
**Example 1 Input : string1 = " PRWSOERIUSFK " string2 = " OSU " Output: Minimum window is "OERIUS"**

In [40]:
string1 = "PRWSOERIUSFK" 
string2 = "OSU"

In [48]:
# string1 = "PRWSOERIUSFK" 
# string2 = "OSU"

# let's find the index of r and g in String and the 
# stor them in index list (index[])  
index=[] 
for x in range(len(string2)):
    if string2[x] in string1: 
        index.append(string1.index(string2[x])) 
  
"""sorting the r and g index's""" 
index.sort() 
  
# save first index in l 
l = len(index) 
low = int(index[0]) 
  
# save  last index in h 
high = int(index[l-1]) 
h = high +1
for i in range(low,h): 
    print(string1[i],end=" ") 

S O E R I U 

# A much more robust code

In [52]:
from collections import Counter, defaultdict 
  
def min_window(str, string2): 
      
    rdict, count = defaultdict(list), Counter(string2) 
    rpos, res = [], ""  
      
    # Loop only over c exist in pattern 
    for i, c in filter(lambda x: x[1] in string2, enumerate(str)):  
        if len(rdict) == count:  
  
            # If reached limit, remove 
            rpos.remove(rdict.pop(0)) 
              
        # Add to dict 
        rdict[i].append(i) 
  
        # Add to list 
        rpos.append(i)  
          
        if (len(rpos) == len(string2) and
           (res =="" or rpos[-1]-rpos[0]<len(res))): 
            res = str[rpos[0]:rpos[-1]+1]  
              
    return res 
  

In [53]:
print(min_window(string1, string2)) 

SOERIU


# <a id='7'>Q16. Write the Python program to find smallest window that contains all characters of the given string?<a/> 


In [ ]:
Original Strings: asdaewsqgtwwsa 
Smallest window that contains all characters of the said string: Daewsqgt

In [54]:
def small_window(str):
    return ''.join(set(str)).capitalize()

In [55]:
small_window('asdaewsqgtwwsa')

'Daqtwgse'

# <a id='7'>Q17. Write the Python program to count number of substrings from a given string of lowercase alphabets with exactly k distinct (given) characters? Input a string (lowercase alphabets): wolf Input k: 4 Number of substrings with exactly 4 distinct characters: 1<a/> 


In [ ]:
Input a string (lowercase alphabets): wolf 
Input k: 4
Number of substrings with exactly 4 distinct characters: 1

In [56]:
def substring_cal(string,k):
    final_str = ''.join(set(string))
    lis = []
    for i in range(0,len(final_str)):
        if i+k > len(final_str):
            break
        lis.append(final_str[i:i+k])
    return len(lis)

In [57]:
substring_cal('paradise' , 4)

4

In [58]:
substring_cal('wolf' , 4)

1

# <a id='7'>Q18. Write the Python program to count number of non-empty substrings of the given string? Input a string: w3resource Number of substrings: 55<a/> 


In [61]:
def non_empty_sub(string):
    lis = [string[i:j] for i in range(0,len(string)) for j in range(i+1,len(string)+1)]
    return len(lis)

In [62]:
non_empty_sub('w3resource')

55

# <a id='7'>Q19. Write the Python program to count number of substrings with same first and last characters of the given string?<a/> 

In [ ]:
Input a string: abcd 
output :   4

In [63]:
def count_sub(string):
    first = string[:1]
    last = string[-1]
    result = 0
    lis = []
    for i in range(0,len(string)):
        for j in range(i,len(string)):
            if string[i] == string[j]:
                result += 1
                lis.append([string[i],string[j]])
    print(lis)
    return result

In [66]:
count_sub('abcd')

[['a', 'a'], ['b', 'b'], ['c', 'c'], ['d', 'd']]


4

# <a id='7'>Q20. Write the Python program to count the number of strings where the string length is 2 or more, and first and last character are same from a given list of strings.<a/> 


In [ ]:
Sample List : ['abc', 'xyz', 'wxw', '1331'] 
Expected Result: 2

In [67]:
def num_str_cnt(x):
    count = 0
    for string in x:
        if len(string) >=2:
            if string[:1] == string[-1]:
                count += 1
    return count

In [68]:
num_str_cnt(['abc', 'xyz', 'wxw', '1331'])

2

# <a id='7'>Q21. Write the Python program to get a list, sorted in increasing order by the last element in each tuple from the given list of non-empty tuples?<a/> 


In [72]:
Sample_List = [(2, 5), (1, 2), (4, 4), (2, 3), (2, 1)] 
# Expected Result = [ (2, 1), (1, 2), (2, 3), (4, 4), (2, 5) ]

In [73]:
m = Sample_List

In [69]:
def sort_turple(m):
    print(sorted(m, key= lambda x: (x[1],x[0])))

In [74]:
sort_turple(m)

[(2, 1), (1, 2), (2, 3), (4, 4), (2, 5)]


# <a id='7'>Q22. Write the Python program to remove duplicates from a list?<a/> 

In [76]:
my_list = ['a','a','a','b','c','d','e','e','f','f','a','c']

In [77]:
def rem_dup(x):
    return list(dict.fromkeys(x))

In [78]:
rem_dup(my_list)

['a', 'b', 'c', 'd', 'e', 'f']

# Or we can write a for loop to remove the duplicates

In [79]:
duplicated = []
for item in my_list:
    if my_list.count(item) > 1:
        if item not in duplicated:
            duplicated.append(item)

In [80]:
print(duplicated)

['a', 'c', 'e', 'f']


# <a id='7'>Q23. Write the Python program to find the list of words that are longer than n from a given list of words?<a/> 


In [81]:
new_list = ['basketball' , 'photosynthesis' , 'aeroplane' , 'placebo' , 'gentleman']

In [92]:
def longest_word(seq , n):
    a = []
    for x in seq:
        if len(x) > n:
            a.append(x)
    return a                 

In [94]:
# note here i am specifying for more than 10
print(longest_word(new_list , 10))

['photosynthesis']


# Or

In [90]:
def longest_w(seq):
    first = seq[0]
    for item in seq[1:]:
        if len(item) > len(first):
            first = item
        return first    

In [91]:
longest_w(new_list)

'photosynthesis'

# <a id='7'>Q24. Write the Python program to print a specified list after removing the 0th, 4th, and 5th elements<a/> 

In [97]:
Sample_List = ['Red', 'Green', 'White', 'Black', 'Pink', 'Yellow'] 

Expected_Output = ['Green', 'White', 'Black']

In [95]:
def remove_list(x):
    remove = []
    for i in [0,4,5]:
        remove.append(x[i])
    for i in remove:
        x.remove(i)
    return x

In [98]:
remove_list(Sample_List)

['Green', 'White', 'Black']

# <a id='7'>Q25. Write the Python program to generate all permutations of a list in Python?<a/> 

In [102]:
from itertools import permutations

def perm(l):
    final = []
    for i in range(1,len(l)):
        perm = permutations(l,i)
        for j in perm:
            final.append(j)
    return final

In [103]:
perm([1,2,3,4])

[(1,),
 (2,),
 (3,),
 (4,),
 (1, 2),
 (1, 3),
 (1, 4),
 (2, 1),
 (2, 3),
 (2, 4),
 (3, 1),
 (3, 2),
 (3, 4),
 (4, 1),
 (4, 2),
 (4, 3),
 (1, 2, 3),
 (1, 2, 4),
 (1, 3, 2),
 (1, 3, 4),
 (1, 4, 2),
 (1, 4, 3),
 (2, 1, 3),
 (2, 1, 4),
 (2, 3, 1),
 (2, 3, 4),
 (2, 4, 1),
 (2, 4, 3),
 (3, 1, 2),
 (3, 1, 4),
 (3, 2, 1),
 (3, 2, 4),
 (3, 4, 1),
 (3, 4, 2),
 (4, 1, 2),
 (4, 1, 3),
 (4, 2, 1),
 (4, 2, 3),
 (4, 3, 1),
 (4, 3, 2)]

# <a id='7'>Q26. Write the Python program to convert a pair of values into a sorted unique array?<a/> 

In [104]:
Original_List = [ (1, 2), (3, 4), (1, 2), (5, 6), (7, 8), (1, 2), (3, 4), (3, 4), (7, 8), (9, 10) ] 

Sorted_Unique_Data = [ 1, 2, 3, 4, 5, 6, 7, 8, 9, 10 ]

In [111]:
from itertools import combinations
import collections

In [115]:
# Now this function shows each separate arrays and also how many times they were counted
def Count_freq(Original_List):
    return collections.Counter(Original_List)

In [116]:
Count_freq(Original_List)

Counter({(1, 2): 3, (3, 4): 3, (5, 6): 1, (7, 8): 2, (9, 10): 1})

# Now Solving the actual question in another way

In [117]:
def sort_array(x):
    output = []
    for item in x:
        for new_item in item:
            output.append(new_item)
    return list(set(output))        

In [118]:
sort_array(Original_List)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# <a id='7'>Q27. Write the Python class to convert an integer to a roman numeral?<a/> 

In [119]:
def Convert_roman(num):
    norm = [1000,900,500,400,100,90,50,40,10,9,5,4,1]
    rom = ['M','CM','D','CD','C','XC','L','XL','X','IX','V','IV','I']
    rom_num = ''
    i = 0
    while num > 0:
        for j in range(num // norm[i]):
            rom_num += rom[i]
            num = num - norm[i]
        i = i + 1
    return rom_num

In [120]:
Convert_roman(100)

'C'

In [121]:
Convert_roman(10)

'X'

In [122]:
Convert_roman(2020)

'MMXX'

# <a id='7'>Q28 Write the Python class to convert a Roman numeral to an integer?<a/> 

In [123]:
def roman_2_int(roman):
    nums = {'M':1000, 'D':500, 'C':100, 'L':50, 'X':10, 'V':5, 'I':1}
    integer = 0
    for i in range(len(roman)):
        value = nums[roman[i]]
        if i+1 < len(roman) and nums[roman[i+1]] > value:
            integer = integer - value
        else:
            integer = integer + value
    return integer

In [126]:
roman_2_int('MMXX')

2020

# <a id='7'>Q29. Write the Python class to find the validity of the string of the parentheses, '(', ')', '{', '}', '[' and '] and the brackets must be closed in the correct order, example - "()" and "()[]{}" are valid but "[)", "({[)]" and "{{{" are invalid.<a/> 


In [127]:
class validity:
    def __init__(self , string):
        self.string = string
        
    def check_validity(self):
        val = 'valid'
        for i in range(len(self.string)-1):
            if self.string[i] == '(' and self.string[i+1]!= ')':
                val = 'invalid'
                break
            if self.string[i] == '{' and self.string[i+1]!= '}':
                val = 'invalid'
                break
            if self.string[i] == '[' and self.string[i+1]!= ']':
                val = 'invalid'
                break
        return val

In [128]:
x = validity('(){[}')
print(x.check_validity())

y = validity('(){}')
print(y.check_validity())

invalid
valid


# <a id='7'>Q30. Write the Python class to get all possible unique subsets from a set of distinct integers?<a/> 

In [ ]:
Input - [4, 5, 6] 
Output - [[], [6], [5], [5, 6], [4], [4, 6], [4, 5], [4, 5, 6]]

In [143]:
class subset:
    def __init__(self,x = []):
        self.x = x
    def permutation(self):
        x = [self.x[i:j] for i in range(0,len(self.x)) for j in range(i,len(self.x)+1)]     
        return [list(x) for x in set(tuple(x) for x in x)]

In [144]:
result = subset([4,5,6])
result.permutation()

[[4, 5], [5, 6], [4], [5], [], [6], [4, 5, 6]]

# <a id='7'>Q31. Write the Python class to find a pair of elements (indices of the two numbers) from a given array whose sum equals the specific target number?<a/> 

In [ ]:
Input: numbers = [10,20,10,40,50,60,70], target=50
Output = 3, 4

In [141]:
class pair:
    def __init__(self,x = []):
        self.x = x
    def subset(self,n):
        return [(i+1,i+2) for i in range(0,len(self.x)-1) if self.x[i] + self.x[i+1] == n]

In [142]:
p = pair([10,20,10,40,50,60,70])
p.subset(50)

[(3, 4)]

# Write a python code to find pairs

In [152]:
lst = [1,5,3,7,9]
k = 12

In [146]:
def find_pair(lst,k):
    return [pair for pair in combinations(lst , 2) if sum (pair) == k ]

In [153]:
find_pair(lst , k)

[(5, 7), (3, 9)]

In [156]:
#Or
find_pair([1,5,3,7,9] , 12)

[(5, 7), (3, 9)]

In [155]:
# here i tested the function with another pair where lst = [2,1,5,7,-1,4] and k = 6
find_pair([2,1,5,7,-1,4] , 6)

[(2, 4), (1, 5), (7, -1)]

# <a id='7'>Q32. Write the Python class to find the three elements that sum to zero from the set of n real numbers?<a/> 

In [238]:
Input_array =  [-25, -10, -7, -3, 2, 4, 8, 10] 

Output  = [[-10, 2, 8], [-7, -3, 10]]

In [250]:
class triple:
    def __init__(self, x = []):
        self.x = x
    def sum_zero(self):
        return [[self.x[i],self.x[j],self.x[k]] for i in range(0,len(self.x)) 
                for j in range(i+1,len(self.x)) 
                for k in range(j+1,len(self.x))
                if self.x[i] + self.x[j] + self.x[k] == 0]


In [251]:
result = triple([-25, -10, -7, -3, 2, 4, 8, 10])
result.sum_zero()

[[-10, 2, 8], [-7, -3, 10]]

# Extra Practice Question
# <a id='7'>Q32a. What is the output of the program to generate fibonaci sequence?<a/> 

In [233]:
def gen_fib(n):
    a = 1
    b = 1
    for i in range(n):
        yield a
        a,b = b , a+b
        
for x in gen_fib(10):
    print(x)

1
1
2
3
5
8
13
21
34
55


# OR

In [236]:
def fib(n):
    a = 1
    b = 1
    output = []
    for i in range(n):
        output.append(a)
        a,b = b , a+b
    return output    

In [237]:
fib(10) 

[1, 1, 2, 3, 5, 8, 13, 21, 34, 55]

# <a id='7'>Q32b What is 5! Note this can also be framed as what is the factorial of 5<a/> 

In [253]:
def factorial(n):
    prod = 1
    while n >= 1:
        prod = prod * n
        n = n - 1
    return prod    

In [254]:
factorial(5)

120

In [255]:
factorial(5/3)

1.6666666666666667

# <a id='7'>Q33. Write the Python class to implement pow(x, n)?<a/> 

In [262]:
class power(object):
    def __init__(self , x):
        self.x = x
    def find_power(self):
        return self.x ** 2

In [263]:
result = power(10)
result.find_power()

100

# <a id='7'>Q34. Write the Python class which has two methods get_String and print_String. get_String accept the string from the user and print_String print the string in upper case.<a/> 

In [264]:
class string:
    def __init__(self):
        pass
    def get_String(self, x):
        self.x = x
    def print_String(self):
        print(self.x.upper())

In [265]:
result = string()
result.get_String('billions')
result.print_String()

BILLIONS


# <a id='7'>Q35. Write the Python class named Rectangle constructed by a length and width and the method which will compute the area of the rectangle?<a/> 

In [266]:
class Rectangle:
    def __init__(self,length,width):
        self.length = length
        self.width = width
    def get_Area(self):
        return self.length*self.width

In [267]:
result = Rectangle(12,10)
result.get_Area()

120

# <a id='7'>Q36. Write the Python class named Circle constructed by the radius and two methods which will compute the area and perimeter of the circle?<a/> 

In [268]:
class Circle:
    def __init__(self,radius):
        self.radius = radius
    def get_area(self):
        from math import pi
        return pi*(self.radius**2)
    def get_perimeter(self):
        from math import pi
        return 2*pi*self.radius

In [276]:
result = Circle(50)
result.get_area()

7853.981633974483

In [277]:
result.get_perimeter()

314.1592653589793

In [278]:
result = Circle(100)
result.get_area()

31415.926535897932

In [279]:
result.get_perimeter()

628.3185307179587

# <a id='7'>Q37. Write the Python program to get the class name of an instance in Python?<a/> 

In [280]:
class class_name:
    pass

result = class_name()
print(result.__class__.__name__)

class_name


# <a id='7'>Q38. Write the Python program to count the number of students of individual class?

Sample data- classes = ( ('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1), )
    
Expected Output- Counter({'VI': 3, 'V': 2, 'VII': 1})<a/> 

In [281]:
classes = (('V', 1), ('VI', 1), ('V', 2), ('VI', 2), ('VI', 3), ('VII', 1),)

In [295]:
def Counter(classes):
    from collections import Counter
    return Counter(classname for classname,student in classes)

In [296]:
Counter(classes)

Counter({'V': 2, 'VI': 3, 'VII': 1})

# <a id='7'>Q39. Write the Python program to create an instance of an OrderedDict using the given dictionary and sort dictionary during the creation and print members of the dictionary in reverse order? .<a/> 

Expected Output- Angola 244. Andorra 376. Algeria 213. Afghanistan 93. Albania 355. 

In reverse order- Albania 355. Afghanistan 93. Algeria 213. Andorra 376. Angola 244

In [298]:
from collections import OrderedDict
my_dict = {'Angola':244,'Andorra':376,'Algeria':213,'Afghanistan':93,'Albania':355}
my_dict = OrderedDict(my_dict)
revDic = OrderedDict()

for k in reversed(my_dict):
    revDic[k] = my_dict[k]


In [299]:
print(revDic)

OrderedDict([('Albania', 355), ('Afghanistan', 93), ('Algeria', 213), ('Andorra', 376), ('Angola', 244)])


# <a id='7'>Q40. Write the Python program to compare two unordered lists (not sets)? Expected Output: False<a/> 

In [301]:
x = [1,2,4,12,13,14]
y = [2,6,9,0,11,5]

length = len(x) if len(l) < len(y) else len(y)
boolean = True
for i in range(0,length-1):
    if sorted(x)[i] != sorted(y)[i]:
        boolean = False
        break
    else:
        boolean = True
print(boolean)

False


# <a id='7'>Q41. Write the Python program to get an array buffer information? Expected Output- Array buffer start address in memory and number of elements. (25855056, 2)<a/> 

In [302]:
from array import *
array_num = array('i',(1,3,4,5,7))
print('Array buffer start address in memory and number of elements',array_num.buffer_info())

Array buffer start address in memory and number of elements (4579077096, 5)


# <a id='7'>Q42. Write the Python program to convert an array to an array of machine values and return the bytes representation? Expected Output- Original array- A1: array('i', [1, 2, 3, 4, 5, 6]) Array of bytes: b'010000000200000003000000040000000500000006000000'<a/> 

In [303]:
from array import *
import binascii
A1 = array('i',[1,2,3,4,5,6])
print("Array of bytes: ",binascii.hexlify(A1.tobytes()))

Array of bytes:  b'010000000200000003000000040000000500000006000000'


# <a id='7'>Q43. Write the Python program to read a string and interpreting the string as an array of machine values? Expected Output- array1- array('i', [7, 8, 9, 10]) Bytes- b'0700000008000000090000000a000000' array2- array('i', [7, 8, 9, 10])<a/> 

In [304]:
from array import array
import binascii
array1 = array('i', [7, 8, 9, 10])
print('array1:', array1)
as_bytes = array1.tobytes()
print('Bytes:', binascii.hexlify(as_bytes))
array2 = array('i')
array2.frombytes(as_bytes)
print('array2:', array2)

array1: array('i', [7, 8, 9, 10])
Bytes: b'0700000008000000090000000a000000'
array2: array('i', [7, 8, 9, 10])


# <a id='7'>Q44. Write the Python program to push three items into the heap and return the smallest item from the heap. Also, return and pop the smallest item from the heap? Expected Output-

items in the heap- ('VI', 1). ('VII', 3). ('VIII', 2). 
    
The smallest item in the heap: ('VI', 1). 
    
Pop the smallest item in the heap: ('VII', 2). ('VIII', 3).

<a/> 

In [305]:
import heapq
heap = []
heapq.heappush(heap,('VII',3))
heapq.heappush(heap,('VI',1))
heapq.heappush(heap,('VIII',2))
print(heap[0])
print(heap.pop(0))

('VI', 1)
('VI', 1)


# <a id='7'>Q45. Write the Python program to locate the left insertion point for a specified value in sorted order? Expected Output: 4 2<a/> 

In [306]:
import numpy as np
def index(a, x):
    i = np.searchsorted(a, x,side='left')
    return i
    
a = [1,2,4,5]
print(index(a, 6))
print(index(a, 3))

4
2


# <a id='7'>Q46. Write the Python program to create the FIFO queue? Expected Output: 0 1 2 3<a/> 

In [307]:
import queue
q = queue.Queue()
#insert items at the end of the queue 
for x in range(4):
    q.put(str(x))
#remove items from the head of the queue 
while not q.empty():
    print(q.get(), end=" ")
print("\n")

0 1 2 3 



# <a id='7'>Q47. Write the Python program to calculate the harmonic sum of n-1. Note: The harmonic sum is the sum of reciprocals of the positive Integers?<a/>

In [308]:
def harmonic_sum(n):
    total = 0
    for i in range(n-1,0,-1):
        total = total + (1/i)
    return total

In [309]:
harmonic_sum(3)

1.5

# <a id='7'>Q48. Write the NumPy program to create a 2d array with 6 on the border and 0 inside? Expected Output- Original array- [ [6 6 6 6 6] [ 6 6 6 6 6] [ 6 6 6 6 6 ] [ 6 6 6 6 6 ] [ 6 6 6 6 ] ]. 6 on the border and 0 inside in the array- [[ 6 6 6 6 6] [ 6 0 0 0 6] [ 6 0 0 0 6] [ 6 0 0 0 6] [ 6 6 6 6 6]].<a/>

In [310]:
import numpy as np
a = np.ones((5,5),dtype='int32') * 6
for i in range(0,5):
    for j in range(0,5):
        if (i == 0 or i == 4):
            a[i][j] = 6
        else:
            a[i][j] = 0
        if (j == 0 or j==4):
            a[i][j] = 6
print(a)

[[6 6 6 6 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 0 0 0 6]
 [6 6 6 6 6]]


# <a id='7'>Q49. Write the NumPy program to create a 8x8 matrix and fill it with the checkerboard pattern? Checkerboard pattern- [[3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3] [3 9 3 9 3 9 3 9] [9 3 9 3 9 3 9 3]].<a/>

In [311]:
import numpy as np
a = np.ones((8,8),dtype='int32') * 9
a[1::2,::2] = 3
a[::2,1::2] = 3
print(a)

[[9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]
 [9 3 9 3 9 3 9 3]
 [3 9 3 9 3 9 3 9]]


# <a id='7'>Q50. Write the NumPy program to create an empty and a full array. Expected Output- [[4.45057637e-308 1.78021527e-306 8.45549797e-307 1.37962049e-306] [1.11260619e-306 1.78010255e-306 9.79054228e-307 4.45057637e-308] [8.45596650e-307 9.34602321e-307 4.94065646e-322 0.00000000e+000]] [[6 6 6] [6 6 6] [6 6 6]]<a/>

In [313]:
import numpy as np
print(np.empty((3,4)))
print(np.ones((3,4)) * 6)

[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]
[[6. 6. 6. 6.]
 [6. 6. 6. 6.]
 [6. 6. 6. 6.]]


# <a id='7'>Q51. Write the NumPy program to convert the values of Centigrade degrees into the Fahrenheit degrees and the centigrade values are stored in the NumPy array.<a/>

In [314]:
def cent_2_fahr(cent = []):
    import numpy as np
    far = np.empty(len(cent))
    for i in range(len(cent)):
        far[i] = (((9*cent[i])/5)+32)
    return far

In [315]:
cent_2_fahr([-27.77, -1, 8.9, 1.11, 37.72])

array([-17.986,  30.2  ,  48.02 ,  33.998,  99.896])

# <a id='7'>Q52. Write the NumPy program to find the real and imaginary parts of an array of complex numbers?<a/>

In [316]:
def ident_complex(com):
    import numpy as np
    real = np.empty(len(com))
    image = np.empty(len(com))
    for i in range(len(com)):
        real[i] = com[i].real
        image[i] = com[i].imag
    return (real,image)

In [317]:
ident_complex([1.00000000+0.j, 0.70710678+0.70710678j])

(array([1.        , 0.70710678]), array([0.        , 0.70710678]))

# <a id='7'>Q53. Write the NumPy program to test whether each element of a 1-D array is also present in the second array? Compare each element of array1 and array2 [ True False False True False] <a/>

In [ ]:
Expected Output- Array1: [ 0 10 20 40 60] 
         Array2: [0, 40] 

In [318]:
import numpy as np
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([0,40])
print(np.in1d(arr1,arr2))

[ True False False  True False]


# <a id='7'>Q54. Write the NumPy program to find common values between two arrays?<a/>

Expected Output- Array1: [ 0 10 20 40 60] 
    
                 Array2: [10, 30, 40] 
            
                 Common values between two arrays- [10 40]

In [319]:
import numpy as np
arr1 = np.array([0,10,20,40,60])
arr2 = np.array([10,30,40])
print(np.intersect1d(arr1,arr2))

[10 40]


# <a id='7'>Q55. Write the NumPy program to get the unique elements of an array?<a/>

Expected Output- Original array- [10 10 20 20 30 30] 

Unique elements of the above array- [10 20 30]

In [320]:
import numpy as np
arr1 = np.array([10,10,20,20,30,30])
arr2 = np.array([[1,1],[2,3]])
print(np.unique(arr1))
print(np.unique(arr2))

[10 20 30]
[1 2 3]


# <a id='7'>Q56. Write the NumPy program to find the set exclusive-or of two arrays. Set exclusive-or will return the sorted, unique values that are in only one (not both) of the input arrays?<a/>

Array1- [ 0 10 20 40 60 80] 

Array2- [10, 30, 40, 50, 70] 

Unique values that are in only one (not both) of the 

input arrays- [ 0 20 30 50 60 70 80

In [321]:
import numpy as np
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([10,30,40,50,70])
np.setxor1d(arr1,arr2)

array([ 0, 20, 30, 50, 60, 70, 80])

# <a id='7'>Q57. Write the NumPy program to test if all elements in an array evaluate to True ? Note: 0 evaluates to False in NumPy.<a/>

In [322]:
import numpy as np
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([-12,10,20,40,60,80])
print(np.all(arr1))
print(np.all(arr2))

False
True


# <a id='7'>Q58 Write the NumPy program to test whether any array element along the given axis evaluates to True? Note: 0 evaluates to False in NumPy.<a/>

In [323]:
import numpy as np
arr1 = np.array([0,10,20,40,60,80])
arr2 = np.array([-12,10,20,40,60,80])
print(np.any(arr1))
print(np.any(arr2))

True
True


# <a id='7'>Q59. Write the NumPy program to construct an array by repeating? Sample array- [1, 2, 3, 4] Expected Output- Original array [1, 2, 3, 4] Repeating 2 times [1 2 3 4 1 2 3 4]<a/>

In [324]:
import numpy as np
arr = np.array([1,2,3,4])
print(np.tile(arr,2))
print(np.tile(arr,3))

[1 2 3 4 1 2 3 4]
[1 2 3 4 1 2 3 4 1 2 3 4]


# <a id='7'>Q60. Write the NumPy program to find the indices of the maximum and minimum values with the given axis of an array? Original array- [1 2 3 4 5 6] Maximum Values- 5 Minimum Values- 0<a/>

In [325]:
import numpy as np
arr = np.array([1,2,3,4,5,6])
print(np.argmax(arr))
print(np.argmin(arr))

5
0


# <a id='7'>Q61. Write the NumPy program compare two arrays using numpy? Array a- [1 2] Array b- [4 5] a > b [False False] a >= b [False False] a < b [ True True] a <= b [ True True]<a/>

In [326]:
import numpy as np 
a = np.array([1,2])
b = np.array([4,5])
print(a > b)
print(a >= b)
print(a < b)
print(a <= b)

[False False]
[False False]
[ True  True]
[ True  True]


# <a id='7'>Q62. Write the NumPy program to sort an along the first, last axis of an array? Sample array- [[2,5],[4,4]] Expected Output- Original array: [[4 6] [2 1]] Sort along the first axis: [[2 1] [4 6]]<a/>

In [327]:
import numpy as np
arr = np.array([[4,6],[2,1]])
print(np.sort(arr,axis=0))
print(np.sort(arr,axis=1))

[[2 1]
 [4 6]]
[[4 6]
 [1 2]]


# <a id='7'>Q63. Write the NumPy program to sort pairs of first name and last name return their indices (first by last name, then by first name). first_names - ( Betsey, Shelley, Lanell, Genesis, Margery ) last_names - ( Battle, Brien, Plotner, Stahl, Woolum ) Expected Output- [1 3 2 4 0]<a/>

In [328]:
import numpy 
first_names = ('Margery','Betsey','Shelley','Lanell','Genesis')
last_names = ('Woolum','Battle','Plotner','Brien','Stahl')
np.lexsort((first_names, last_names))

array([1, 3, 2, 4, 0])

# <a id='7'>Q64. Write the NumPy program to get the values and indices of the elements that are bigger than 10 in the given array? Original array- [[ 0 10 20] [20 30 40]] Values bigger than 10 = [20 20 30 40] Their indices are (array([0, 1, 1, 1]), array([2, 0, 1, 2]))<a/>

In [329]:
import numpy as np
arr = np.array([[0,10,20],[20,30,40]])
print(arr[arr>10])
print(np.nonzero(arr>10))

[20 20 30 40]
(array([0, 1, 1, 1]), array([2, 0, 1, 2]))


# <a id='7'>Q65. Write the NumPy program to find the memory size of a NumPy array? Expected Output- 128 bytes<a/>

In [330]:
import numpy as np
arr = np.zeros((4,4))
print(arr.size * arr.itemsize)

128


# <a id='7'>Q66. Write the NumPy program to create an array of ones and an array of zeros? Expected Output- Create an array of zeros Default type is float [[ 0. 0.]] Type changes to int [[0 0]] Create an array of ones Default type is float [[ 1. 1.]] Type changes to int [[1 1]]<a/>

In [331]:
import numpy as np
print(np.zeros(2,dtype='int'))
print(np.ones(2,dtype='int'))

[0 0]
[1 1]


# <a id='7'>Q67. Write the NumPy program to change the dimension of an array? Expected Output- 6 rows and 0 columns (6,) (3, 3) -> 3 rows and 3 columns [[1 2 3] [4 5 6] [7 8 9]] Change array shape to (3, 3) -> 3 rows and 3 columns [[1 2 3] [4 5 6] [7 8 9]]<a/>

In [332]:
import numpy as np
print(np.array([1,2,3,4,5,6,7,8,9]))
print(np.array([1,2,3,4,5,6,7,8,9]).reshape(3,3))

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


# <a id='7'>Q68. Write the NumPy program to create a new shape to an array without changing its data ? Reshape 3x2- [[1 2] [3 4] [5 6]] Reshape 2x3- [[1 2 3] [4 5 6]]<a/>

In [333]:
import numpy as np
print(np.array([[1,2],[3,4],[5,6]]))
print(np.array([[1,2],[3,4],[5,6]]).reshape(2,3))

[[1 2]
 [3 4]
 [5 6]]
[[1 2 3]
 [4 5 6]]


# <a id='7'>Q69. Write the NumPy program to create a new array of 3*5, filled with 2? Expected Output- [[2 2 2 2 2] [2 2 2 2 2] [2 2 2 2 2]] [[2 2 2 2 2] [2 2 2 2 2] [2 2 2 2 2]]<a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>

In [ ]:
# <a id='7'><a/>